provider: "cache"         # cache | polygon | alpaca
symbols: ["QQQ", "PSQ"]
lookback_days: 800        # how many daily bars to fetch when seeding
force_refresh: false      # if true, ignore existing cache

staleness:
  max_days_ok: 3   # Warn if price_common_date is older than this many calendar days

# Provider-specific
polygon:
  base_url: "https://api.polygon.io/v2/aggs/ticker/{symbol}/range/1/day/{from}/{to}"
alpaca:
  base_url: "https://data.alpaca.markets/v2/stocks/{symbol}/bars?timeframe=1Day&start={from}&end={to}&limit=10000"
