trend:
  fast_ma: 20
  slow_ma: 250

weights:
  base_risk: 1.0           # 1.0 = 100% nominal exposure
  max_exposure_pct: 1.0    # cap per side (100%)
  min_exposure_pct: 0.0
  extension_factor: 2.5    # how sharply exposure drops as extension increases
  bb_period: 20
  bb_std: 2.0

confirmation:                # NEW
  momentum_requires_close_above_fast: true
  momentum_requires_slope_up: true     # fast MA slope > 0 for momentum boost

vol_dampener:                # NEW
  enabled: true
  lookback_days: 20          # realized vol window
  cap_rvol: 0.25             # if rVol20 > 25%, start damping
  floor_scale: 0.60          # never scale below 60% of the post-extension weight
