# Multi-layered risk controls
position_sizing:
  risk_budget_pct: 0.015     # risk 1.5% equity per position (base)
  atr_len: 14
  max_position_pct: 0.60     # cap single exposure at 60%

regime_adjustments:
  vix_soft: 25               # scale down above this
  vix_hard: 35               # block new risk
  qqq_20d_vol_max: 0.40      # block in extreme realized vol

circuit_breakers:
  fomc_blackout_days: [-1, 1]    # day before & after
  options_expiry_caution: true
  earnings_blackout: false        # ETFs don't report earnings
