# Multi-layered risk controls
position_sizing:
  risk_budget_pct: 0.015     # risk 1.5% equity per position (base)
  atr_len: 14
  max_position_pct: 0.60     # cap single exposure at 60%

regime_adjustments:
  vix_soft: 25               # scale down above this
  vix_hard: 35               # block new risk
  qqq_20d_vol_max: 0.40      # block in extreme realized vol

circuit_breakers:
  fomc_blackout_days: [-1, 1]    # day before & after
  options_expiry_caution: true
  earnings_blackout: false        # ETFs don't report earnings

turnover:
  max_pct_of_equity: 0.15   # 15% of equity per day (change this to taste)
  mode: "clamp"             # "clamp" (scale down) or "skip" (do nothing)

cadence:
  enabled: true         # turn guard on/off
  min_days_between: 1   # e.g., 1=don't trade the same symbol on consecutive sessions
  symbols: ["QQQ","PSQ"]  # which symbols to enforce; leave empty to apply to all execution symbols

exposure_threshold:
  enabled: true
  min_delta_abs: 0.01    # skip if |desired – prev| < 1 %

coalescing:
  enabled: true
  close_dust_shares: 1.0         # if remaining position < this, treat as dust → single intent
  min_open_notional: 200.0       # don't open new side if notional < this (pairs with your constraints)
  prefer_single_leg_if_net_small: true  # if sell_to_zero and buy_new nearly cancel, emit only larger leg
